#remote_theme: chrisrhymes/bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme@v0.14.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: FLEGREA Project
description: Federated Learning for Generative Emulation of Advanced Persistent Threats - PRIN 2022 Project

#show_downloads: false
show_sidebar: true

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      hero_image: /assets/images/hero.jpg

collections:
  datasets:
    output: false
  publications:
    output: false
